apiVersion: v1
kind: Secret
metadata:
  name: vulcano-community-env
  namespace: default
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Z1bGNhbm9fYXBwOnZ1bGNhbm9fc2VjdXJlXzIwMjRAMTI3LjAuMC4xOjU0MzIvdnVsY2Fub19jb21tdW5pdHk=
  NEXTAUTH_SECRET: dnVsY2Fub19jb21tdW5pdHlfc2VjcmV0X2tleV8yMDI0X3NlY3VyZQ==
  NEXTAUTH_URL: aHR0cHM6Ly92dWxjYW5vLWNvbW11bml0eS5kZG5zLm5ldA==